# file=open("info.txt","r")
# content=file.readlines()
# print(content)
# file.close()
# print()

# file=open("info.txt","w")
# file.write("Hello, World!\n")
# file=open("info.txt","r")
# content=file.readlines()
# print(content)
# file.close()
# file=open("info.txt","w")
# file.write("welcome to acuvate\n")
# file=open("info.txt","r")
# content=file.readlines()
# print(content)


file=open("info1.py","w")
file.write("from datetime import datetime\n""now=datetime.now()\n""print(now)")
file=open("info1.py","r")
content=file.read()
print(content)
file.close()
exec(content)