file=open("Student.txt","w")
name=input("Enter your name: ")
age=int(input("Enter age: "))
marks=int(input("Enter your marks: "))
file.write(name+"\n")
file.write(str(age)+"\n")
file.write(str(marks)+"\n")
file.close()
file=open("Student.txt","r")
info=file.read()
print(info)
